Drop table associative;
Drop table movies;
Drop table genres;
CREATE TABLE movies (id varchar(3) primary key not null,title VARCHAR(20), release_date date,  duration int(4),score int(2));
CREATE TABLE  genres(id varchar(3) primary key not null, name varchar(100));
CREATE TABLE associative(id_movie varchar(3) , id_genres varchar(3));
Alter table associative add constraint fk_movies FOREIGN KEY (id_movie)REFERENCES movie(id) ON DELETE CASCADE;
Alter table associative add constraint fk_genres FOREIGN KEY (id_genres)REFERENCES genres(id) ON DELETE CASCADE;
Insert into movies values('123','Harry Potter','17-12-01',200,3);
Insert into movies values('124','Godfather','74-05-13',154,5);
Insert into movies values('125','Fightclub','94-10-11',189,4);
Insert into genres values('1','Drama');
Insert into genres values('2','Action');
Insert into genres values('3','Thriller');
Insert into associative values('123','1');
Insert into associative values('124','1');
Insert into associative values('125','2');